# Generated by Django 5.1.3 on 2026-02-17 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_patient_patient_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Patient',
        ),
    ]
